title: Aloha Eats
description: Browse and filter through food options on UH Manoa Campus
google_analytics:
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
github:
  is_project_page: true
  repository_url: https://github.com/ManoaMunchies/manoa-munchies.github.io
gems:
  - jekyll-mentions