title: Manoa Munchies
description: The Manoa Munchie project page
google_analytics:
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
github:
  is_project_page: true
  repository_url: https://github.com/ManoaMunchies/manoa-munchies.github.io
gems:
  - jekyll-mentions