title: ManoaMunchies
description: Profiles, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-dinky
github:
  is_project_page: true
  repository_url: https://github.com/ManoaMunchies/manoa-munchies.github.io
gems:
  - jekyll-mentions